name: smart_village_app
description: Smart Village Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 FIREBASE
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.3.0
  firebase_messaging: ^16.0.0

  # 📊 ANALYTICS
  fl_chart: ^0.68.0

  # 🌐 URL LAUNCHER
  url_launcher: ^6.3.0

  # 📷 IMAGE UPLOAD
  image_picker: ^1.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # 🚀 APP ICON
  flutter_launcher_icons: ^0.13.1

  # 🚀 SPLASH SCREEN
  flutter_native_splash: ^2.4.1
  #change app package name
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

# 🚀 APP ICON CONFIG
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

# 🚀 SPLASH SCREEN CONFIG
flutter_native_splash:
  color: "#4CAF50"
  image: assets/icon/icon.png

  android: true
  ios: true