// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhPNTQgT57HsBOpxQAqlI_Car_c4qdzw',
    appId: '1:1058976895782:web:de438d320c028be1b627e7',
    messagingSenderId: '1058976895782',
    projectId: 'smart-village-app-192a5',
    authDomain: 'smart-village-app-192a5.firebaseapp.com',
    storageBucket: 'smart-village-app-192a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBesC7SySKTgnTIdNkgO1ns6GbiML6swVA',
    appId: '1:1058976895782:android:662b9fc91d0e496eb627e7',
    messagingSenderId: '1058976895782',
    projectId: 'smart-village-app-192a5',
    storageBucket: 'smart-village-app-192a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjScGziHgisPKTg-uu_uJGCZnhcQgTtA',
    appId: '1:1058976895782:ios:c697f0b02c10cdc0b627e7',
    messagingSenderId: '1058976895782',
    projectId: 'smart-village-app-192a5',
    storageBucket: 'smart-village-app-192a5.firebasestorage.app',
    iosBundleId: 'com.example.smartVillageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKjScGziHgisPKTg-uu_uJGCZnhcQgTtA',
    appId: '1:1058976895782:ios:c697f0b02c10cdc0b627e7',
    messagingSenderId: '1058976895782',
    projectId: 'smart-village-app-192a5',
    storageBucket: 'smart-village-app-192a5.firebasestorage.app',
    iosBundleId: 'com.example.smartVillageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhPNTQgT57HsBOpxQAqlI_Car_c4qdzw',
    appId: '1:1058976895782:web:364481b328d41f08b627e7',
    messagingSenderId: '1058976895782',
    projectId: 'smart-village-app-192a5',
    authDomain: 'smart-village-app-192a5.firebaseapp.com',
    storageBucket: 'smart-village-app-192a5.firebasestorage.app',
  );
}
